# Generated by Django 4.2.7 on 2023-12-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'member')], default='member', max_length=9, verbose_name='статус пользователя'),
        ),
    ]
