# Generated by Django 4.2.7 on 2023-12-18 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateField(default=datetime.date.today, verbose_name='дата последнего входа'),
        ),
    ]
