# Generated by Django 4.2.7 on 2023-11-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_drf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='url',
            field=models.URLField(max_length=300, verbose_name='ссылка'),
        ),
    ]
