# Generated by Django 4.2.7 on 2023-11-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_drf', '0003_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='ссылка'),
        ),
    ]
