# Generated by Django 4.2.7 on 2023-11-29 19:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_drf', '0004_alter_lesson_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='дата оплаты')),
                ('total', models.PositiveIntegerField(verbose_name='сумма оплаты')),
                ('online_payment', models.BooleanField(blank=True, default=False, null=True, verbose_name='оплата переводом на счет')),
                ('cash_payment', models.BooleanField(blank=True, default=False, null=True, verbose_name='оплата наличными')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_drf.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_drf.lesson')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
    ]
