# Generated by Django 4.2.7 on 2023-12-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_drf', '0010_alter_subscription_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=500, verbose_name='цена'),
        ),
    ]
