# Generated by Django 4.2.7 on 2023-12-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_drf', '0011_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='stipe_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Stripe ID'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='сумма оплаты'),
        ),
    ]
