# Generated by Django 4.2.7 on 2023-12-09 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_drf', '0012_payments_stipe_id_alter_payments_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='stipe_id',
            new_name='stripe_id',
        ),
    ]
