# Generated by Django 4.2.7 on 2023-12-09 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_drf', '0014_remove_payments_stripe_id_payments_client_secret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='client_secret',
            new_name='stripe_id',
        ),
    ]
