# Generated by Django 4.2.7 on 2023-12-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_drf', '0015_rename_client_secret_payments_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='статус оплаты'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Stripe ID'),
        ),
    ]
