# Generated by Django 4.2.7 on 2023-12-09 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_drf', '0016_payments_payment_status_alter_payments_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='payment_status',
        ),
    ]
